[package]
name = "linkstamp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
html-escape = "0.2"
idm = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.7"
